apiVersion: batch/v1
kind: CronJob
metadata:
  name: plex-meta-manager
  namespace: plex-meta-manager
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
          containers:
            - name: plex-meta-manager
              image: meisnate12/plex-meta-manager:v1.17.3
              imagePullPolicy: IfNotPresent
              args: [ "--run", "--read-only-config" ]
              resources:
                limits:
                  memory: 1024Mi
                requests:
                  cpu: 100m
                  memory: 1024Mi
              volumeMounts:
                - name: config
                  mountPath: /config
                - name: pmm-config
                  mountPath: /config/config.yml
                  subPath: config.yml
                - name: movie-config
                  mountPath: /config/movie-config.yml
                  subPath: movie-config.yml
                - name: kids-movie-config
                  mountPath: /config/kids-movie-config.yml
                  subPath: kids-movie-config.yml
          volumes:
            - name: config
              persistentVolumeClaim:
                claimName: plex-meta-manager
            - name: pmm-config
              secret:
                secretName: pmm-config
            - configMap:
                name: movie-config
              name: movie-config
            - configMap:
                name: kids-movie-config
              name: kids-movie-config
          restartPolicy: OnFailure